"""
Attack Engine Base Interface
Abstract base class defining standard structure and outcomes for cyber and quantum attacks.
"""

from __future__ import annotations
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Dict, Any, List, Optional, Tuple

from teleshield.qds.models import QDSSignature, KeySlot


@dataclass
class AttackExecutionResult:
    """Encapsulates the modifications and metadata generated by an attack execution."""
    attack_type: str
    description: str
    target_blocks: List[int]
    strength: float
    ground_truth_modified: bool
    manipulated_signature: Optional[QDSSignature] = None
    manipulated_slots: Optional[Dict[Tuple[int, int, int], KeySlot]] = None
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "attack_type": self.attack_type,
            "description": self.description,
            "target_blocks": self.target_blocks,
            "strength": self.strength,
            "ground_truth_modified": self.ground_truth_modified,
            "metadata": self.metadata,
        }


class BaseAttack(ABC):
    """Abstract base class for all simulated attacks."""

    def __init__(self, name: str, description: str, strength: float = 1.0) -> None:
        self.name = name
        self.description = description
        self.strength = max(0.0, min(1.0, float(strength)))

    @abstractmethod
    def execute(self, **kwargs) -> AttackExecutionResult:
        """Executes attack against given session, signature, or quantum states."""
        pass

    def __repr__(self) -> str:
        return f"{self.__class__.__name__}(strength={self.strength})"
